import type { QuizQuestion } from '@/types';

// 20-question quiz covering all dimensions of the recommendation algorithm
export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ── BACKGROUND (Q1–Q4) ────────────────────────────────────
  {
    id: 'country_of_origin',
    step: 1,
    type: 'single_choice',
    category: 'background',
    question: 'Which country are you studying from?',
    subtitle: 'Helps us find country-specific scholarships',
    options: [
      { value: 'India', label: 'India', icon: '🇮🇳' },
      { value: 'China', label: 'China', icon: '🇨🇳' },
      { value: 'Nepal', label: 'Nepal', icon: '🇳🇵' },
      { value: 'Pakistan', label: 'Pakistan', icon: '🇵🇰' },
      { value: 'Philippines', label: 'Philippines', icon: '🇵🇭' },
      { value: 'Indonesia', label: 'Indonesia', icon: '🇮🇩' },
      { value: 'Vietnam', label: 'Vietnam', icon: '🇻🇳' },
      { value: 'Bangladesh', label: 'Bangladesh', icon: '🇧🇩' },
      { value: 'Sri Lanka', label: 'Sri Lanka', icon: '🇱🇰' },
      { value: 'Other', label: 'Other country', icon: '🌏' },
    ],
    required: true,
    weight: 0.5,
  },
  {
    id: 'current_qualification',
    step: 2,
    type: 'single_choice',
    category: 'background',
    question: 'What is your highest completed qualification?',
    subtitle: 'This determines which programs you can apply for',
    options: [
      { value: 'High School', label: 'High School / Year 12', icon: '🏫' },
      { value: 'Diploma', label: 'Diploma / Foundation', icon: '📜' },
      { value: 'Bachelor', label: "Bachelor's Degree", icon: '🎓' },
      { value: 'Master', label: "Master's Degree", icon: '🎓' },
      { value: 'PhD', label: 'PhD / Doctorate', icon: '🔬' },
    ],
    required: true,
    weight: 1.0,
  },
  {
    id: 'study_level',
    step: 3,
    type: 'single_choice',
    category: 'background',
    question: 'What level of study are you seeking in Australia?',
    options: [
      {
        value: 'Undergraduate',
        label: 'Undergraduate',
        icon: '📚',
        description: "Bachelor's degree (3–4 years)",
      },
      {
        value: 'Postgraduate',
        label: 'Postgraduate',
        icon: '🎓',
        description: "Master's or Graduate Diploma (1–2 years)",
      },
    ],
    required: true,
    weight: 2.0,
  },
  {
    id: 'work_experience_years',
    step: 4,
    type: 'single_choice',
    category: 'background',
    question: 'How many years of work experience do you have?',
    options: [
      { value: '0', label: 'None (student)', icon: '📖' },
      { value: '1', label: '1 year', icon: '💼' },
      { value: '2', label: '2 years', icon: '💼' },
      { value: '3', label: '3 years', icon: '💼' },
      { value: '5', label: '4–5 years', icon: '💼' },
      { value: '7', label: '6+ years', icon: '💼' },
    ],
    required: true,
    weight: 0.8,
  },

  // ── ACADEMIC (Q5–Q9) ──────────────────────────────────────
  {
    id: 'ielts_score',
    step: 5,
    type: 'single_choice',
    category: 'academic',
    question: 'What is your IELTS overall band score?',
    subtitle: 'Or expected score if you plan to take it soon',
    options: [
      { value: '5.0', label: '5.0 or below' },
      { value: '5.5', label: '5.5' },
      { value: '6.0', label: '6.0' },
      { value: '6.5', label: '6.5' },
      { value: '7.0', label: '7.0' },
      { value: '7.5', label: '7.5' },
      { value: '8.0', label: '8.0+' },
    ],
    required: true,
    weight: 2.0,
  },
  {
    id: 'gpa_score',
    step: 6,
    type: 'single_choice',
    category: 'academic',
    question: 'What is your undergraduate GPA (or equivalent)?',
    subtitle: 'Important for postgraduate applications',
    options: [
      { value: '2.0', label: 'Below 2.5 / Pass' },
      { value: '2.7', label: '2.5–2.9 / Credit' },
      { value: '3.0', label: '3.0–3.4 / Merit' },
      { value: '3.5', label: '3.5–3.6 / Distinction' },
      { value: '3.7', label: '3.7–3.9 / High Distinction' },
      { value: '4.0', label: '4.0 / First Class Honours' },
      { value: '0', label: "Not applicable / I'm in high school" },
    ],
    required: false,
    weight: 1.5,
  },
  {
    id: 'gmat_score',
    step: 7,
    type: 'single_choice',
    category: 'academic',
    question: 'Do you have a GMAT score? (MBA programs often require it)',
    options: [
      { value: '', label: "No / Not applicable", icon: '❌' },
      { value: '500', label: 'Below 550' },
      { value: '580', label: '550–599' },
      { value: '620', label: '600–649' },
      { value: '660', label: '650–699' },
      { value: '700', label: '700+', icon: '⭐' },
    ],
    required: false,
    weight: 1.0,
  },
  {
    id: 'research_or_coursework',
    step: 8,
    type: 'single_choice',
    category: 'academic',
    question: 'Do you prefer research or coursework-based study?',
    options: [
      {
        value: 'coursework',
        label: 'Coursework',
        icon: '📝',
        description: 'Structured classes, assignments, exams',
      },
      {
        value: 'research',
        label: 'Research',
        icon: '🔬',
        description: 'Thesis, independent project, academic pathway',
      },
      {
        value: 'either',
        label: 'Either is fine',
        icon: '🤷',
        description: "I'm open to both",
      },
    ],
    required: true,
    weight: 0.8,
  },

  // ── FIELD & COURSE PREFERENCES (Q9–Q13) ──────────────────
  {
    id: 'field_of_study',
    step: 9,
    type: 'single_choice',
    category: 'preferences',
    question: 'What field of study are you most interested in?',
    options: [
      { value: 'Engineering', label: 'Engineering', icon: '⚙️' },
      { value: 'Business', label: 'Business / MBA', icon: '💼' },
      { value: 'IT', label: 'IT / Computer Science', icon: '💻' },
      { value: 'Medicine', label: 'Medicine / Health', icon: '🏥' },
      { value: 'Science', label: 'Science / Research', icon: '🔬' },
      { value: 'Agriculture', label: 'Agriculture', icon: '🌾' },
      { value: 'Law', label: 'Law', icon: '⚖️' },
      { value: 'Design', label: 'Design / Creative', icon: '🎨' },
      { value: 'Health', label: 'Health / Nursing', icon: '🩺' },
      { value: 'Other', label: 'Other / Undecided', icon: '🤔' },
    ],
    required: true,
    weight: 2.5,
  },
  {
    id: 'preferred_specializations',
    step: 10,
    type: 'multi_choice',
    category: 'preferences',
    question: 'Which specializations interest you most?',
    subtitle: 'Select up to 3',
    options: [
      { value: 'AI', label: 'Artificial Intelligence' },
      { value: 'Cybersecurity', label: 'Cybersecurity' },
      { value: 'Cloud Computing', label: 'Cloud Computing' },
      { value: 'Data Science', label: 'Data Science' },
      { value: 'Civil', label: 'Civil Engineering' },
      { value: 'Mechanical', label: 'Mechanical Engineering' },
      { value: 'Software', label: 'Software Engineering' },
      { value: 'Finance', label: 'Finance' },
      { value: 'Marketing', label: 'Marketing' },
      { value: 'Strategy', label: 'Strategy / Management' },
      { value: 'Mining', label: 'Mining' },
      { value: 'Sustainable Farming', label: 'Sustainable Agriculture' },
      { value: 'General Practice', label: 'General Practice' },
      { value: 'UX/UI', label: 'UX / UI Design' },
    ],
    required: false,
    weight: 1.5,
  },
  {
    id: 'preferred_duration',
    step: 11,
    type: 'single_choice',
    category: 'preferences',
    question: 'What is your preferred course duration?',
    options: [
      { value: '1', label: '1 year (accelerated)', icon: '⚡' },
      { value: '1.5', label: '1.5 years', icon: '📅' },
      { value: '2', label: '2 years (standard)', icon: '📅' },
      { value: '3', label: '3 years', icon: '📅' },
      { value: '4', label: '4 years', icon: '📅' },
      { value: '0', label: 'No preference', icon: '🤷' },
    ],
    required: false,
    weight: 0.5,
  },

  // ── LOCATION (Q12–Q13) ─────────────────────────────────────
  {
    id: 'preferred_state',
    step: 12,
    type: 'multi_choice',
    category: 'preferences',
    question: 'Which Australian states/territories are you open to?',
    subtitle: 'Select all that apply',
    options: [
      { value: 'New South Wales', label: 'New South Wales (Sydney)', icon: '🏙️' },
      { value: 'Victoria', label: 'Victoria (Melbourne)', icon: '☕' },
      { value: 'Queensland', label: 'Queensland (Brisbane/Gold Coast)', icon: '☀️' },
      { value: 'Western Australia', label: 'Western Australia (Perth)', icon: '🌅' },
      { value: 'South Australia', label: 'South Australia (Adelaide)', icon: '🍷' },
      { value: 'Australian Capital Territory', label: 'ACT (Canberra)', icon: '🏛️' },
      { value: 'Tasmania', label: 'Tasmania (Hobart)', icon: '🌿' },
      { value: 'Any', label: 'Open to anywhere', icon: '🇦🇺' },
    ],
    required: true,
    weight: 1.5,
  },

  // ── FINANCIAL (Q14–Q16) ────────────────────────────────────
  {
    id: 'annual_budget',
    step: 13,
    type: 'single_choice',
    category: 'financial',
    question: 'What is your annual tuition budget (AUD)?',
    subtitle: "This is tuition only, not including living costs",
    options: [
      { value: '30000', label: 'Under $35,000/year', icon: '💰' },
      { value: '40000', label: '$35,000–$44,999/year', icon: '💰' },
      { value: '50000', label: '$45,000–$54,999/year', icon: '💰' },
      { value: '60000', label: '$55,000–$64,999/year', icon: '💰' },
      { value: '70000', label: '$65,000+/year', icon: '💰' },
    ],
    required: true,
    weight: 2.0,
  },
  {
    id: 'needs_scholarship',
    step: 14,
    type: 'single_choice',
    category: 'financial',
    question: 'Are you looking for scholarship opportunities?',
    options: [
      { value: 'yes', label: 'Yes — scholarships are important to me', icon: '🏆' },
      { value: 'nice_to_have', label: 'Nice to have, not essential', icon: '✨' },
      { value: 'no', label: "No — I've got funding sorted", icon: '✅' },
    ],
    required: true,
    weight: 1.0,
  },

  // ── CAREER (Q16–Q19) ──────────────────────────────────────
  {
    id: 'career_goals',
    step: 15,
    type: 'multi_choice',
    category: 'career',
    question: 'What are your career goals after graduating?',
    subtitle: 'Select up to 3',
    options: [
      { value: 'Software Engineer', label: 'Software Engineer / Developer', icon: '💻' },
      { value: 'Data Scientist', label: 'Data Scientist / AI Engineer', icon: '📊' },
      { value: 'Business Manager', label: 'Business Manager / Director', icon: '💼' },
      { value: 'Consultant', label: 'Management Consultant', icon: '🤝' },
      { value: 'Engineer', label: 'Civil / Mechanical / Electrical Engineer', icon: '⚙️' },
      { value: 'Doctor', label: 'Doctor / Medical Specialist', icon: '🩺' },
      { value: 'Researcher', label: 'Academic / Researcher', icon: '🔬' },
      { value: 'Entrepreneur', label: 'Entrepreneur / Startup', icon: '🚀' },
      { value: 'Lawyer', label: 'Lawyer / Legal Professional', icon: '⚖️' },
      { value: 'Other', label: 'Other career path', icon: '🌟' },
    ],
    required: true,
    weight: 1.5,
  },
  {
    id: 'salary_importance',
    step: 16,
    type: 'single_choice',
    category: 'career',
    question: 'How important is graduate salary to your decision?',
    options: [
      { value: 'high', label: 'Very important — salary is a top priority', icon: '💵' },
      { value: 'medium', label: 'Somewhat important', icon: '📈' },
      { value: 'low', label: "Not important — I'm focused on passion/impact", icon: '❤️' },
    ],
    required: true,
    weight: 1.0,
  },
  {
    id: 'ranking_importance',
    step: 17,
    type: 'single_choice',
    category: 'preferences',
    question: 'How important is university ranking to you?',
    options: [
      {
        value: 'high',
        label: 'Very important — I want a top-ranked university',
        icon: '⭐',
      },
      { value: 'medium', label: 'Somewhat important', icon: '📊' },
      {
        value: 'low',
        label: "Not important — fit and value matter more",
        icon: '🤝',
      },
    ],
    required: true,
    weight: 1.0,
  },

  // ── INTAKE & FINAL (Q18–Q20) ─────────────────────────────
  {
    id: 'expected_intake',
    step: 18,
    type: 'single_choice',
    category: 'preferences',
    question: 'When are you planning to start your studies?',
    options: [
      { value: 'Feb2026', label: 'February 2026', icon: '📅' },
      { value: 'Jul2026', label: 'July 2026', icon: '📅' },
      { value: 'Feb2027', label: 'February 2027', icon: '📅' },
      { value: 'later', label: 'Still exploring', icon: '🤔' },
    ],
    required: true,
    weight: 0.3,
  },
  {
    id: 'city_or_regional',
    step: 19,
    type: 'single_choice',
    category: 'preferences',
    question: 'Do you prefer a city or regional university?',
    options: [
      { value: 'city', label: 'City — I want the urban experience', icon: '🏙️' },
      { value: 'regional', label: 'Regional — quieter, potentially cheaper', icon: '🌳' },
      { value: 'either', label: 'No preference', icon: '🤷' },
    ],
    required: true,
    weight: 0.5,
  },
  {
    id: 'additional_notes',
    step: 20,
    type: 'text_input',
    category: 'background',
    question: 'Anything else we should know?',
    subtitle: 'Optional — e.g. specific universities you love, health requirements, etc.',
    placeholder: 'E.g. I want a university close to an international airport...',
    required: false,
    weight: 0.0,
  },
];

export const TOTAL_STEPS = QUIZ_QUESTIONS.length;
export const FREE_PREVIEW_STEPS = 10; // Steps shown without account
